//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_test.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookShop
    {
        public int BookShopID { get; set; }
        public int AutherID { get; set; }
        public int BookID { get; set; }
    
        public virtual Auhtor Auhtor { get; set; }
        public virtual Book Book { get; set; }
    }
}
