//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_test.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryChanx
    {
        public int CategoryChangeID { get; set; }
        public int CatergoryID { get; set; }
        public string OldCategoryName { get; set; }
        public string NewCategoryName { get; set; }
    }
}
