//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_test.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPriceChanx
    {
        public int ProductPriceChangeID { get; set; }
        public int ProductID { get; set; }
        public decimal OldPrice { get; set; }
        public decimal NewPrice { get; set; }
        public System.DateTime ChangedDate { get; set; }
        public int UserId { get; set; }
    }
}
